sudo: required
language: elixir

elixir:
  - 1.9

cache:
  - apt
  - directories:
    - ~/.mongodb
    - ~/.mix

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g mongodb-version-manager
  - m use $MONGOVERSION
  - bash ./start_mongo.bash
  - mkdir db

before_script:
  - export PATH=$(m path):$PATH
  - echo $PATH
  - mongod --fork --logpath mongo.log --dbpath db

script:
  - mix test
#  - mix dialyzer

env:
  matrix:
    - MONGOVERSION=3.4.20 TRAVIS_NODE_VERSION=4
    - MONGOVERSION=3.6.12 TRAVIS_NODE_VERSION=4
    - MONGOVERSION=4.0.9 TRAVIS_NODE_VERSION=4
