language: elixir
elixir:
  - 1.2.4
cache:
  - apt
  - directories:
    - ~/.mongodb
before_install:
  - npm install -g mongodb-version-manager
  - m use $MONGOVERSION
  - mkdir db
before_script:
  - mongod --fork --logpath mongo.log --dbpath db
env:
  matrix:
    - MONGOVERSION=2.4.14
    - MONGOVERSION=2.6.12
    - MONGOVERSION=3.0.11
    - MONGOVERSION=3.2.4
matrix:
  include:
    - elixir: 1.0.5
      otp_release: 17.5
      env: MONGOVERSION=3.2.4
    - elixir: 1.1.1
      otp_release: 17.5
      env: MONGOVERSION=3.2.4
notifications:
  recipients:
    - eric.meadows.jonsson@gmail.com
