language: elixir
elixir:
  - 1.2.6
  - 1.3.4
cache:
  - apt
  - directories:
    - ~/.mongodb
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g mongodb-version-manager
  - m use $MONGOVERSION
  - mkdir db
before_script:
  - sudo service mongodb stop
  - export PATH=$(m path):$PATH
  - mongod --fork --logpath mongo.log --dbpath db
env:
  matrix:
    - MONGOVERSION=2.4.14
    - MONGOVERSION=2.6.12
    - MONGOVERSION=3.0.12
    - MONGOVERSION=3.2.10
    - MONGOVERSION=3.4.0
notifications:
  recipients:
    - eric.meadows.jonsson@gmail.com
