language: elixir
otp_release:
  - 17.4
cache: apt
before_install:
  - npm install -g mongodb-version-manager
  - m use $MONGOVERSION
  - mkdir db
before_script:
  - mongod --fork --logpath mongo.log --dbpath db
env:
  matrix:
    - MONGOVERSION=2.4.14
    - MONGOVERSION=2.6.10
    - MONGOVERSION=3.0.3
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - eric.meadows.jonsson@gmail.com
