sudo: required
language: elixir

elixir:
  - 1.3
  - 1.4
  - 1.5

cache:
  - apt
  - directories:
    - ~/.mongodb

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g mongodb-version-manager
  - m use $MONGOVERSION
  - bash ./start_mongo.bash
  - mkdir db

before_script:
  - export PATH=$(m path):$PATH
  - echo $PATH
  - mongod --fork --logpath mongo.log --dbpath db

env:
  matrix:
    - MONGOVERSION=2.4.14 TRAVIS_NODE_VERSION=4
    - MONGOVERSION=2.6.12 TRAVIS_NODE_VERSION=4
    - MONGOVERSION=3.0.15 TRAVIS_NODE_VERSION=4
    - MONGOVERSION=3.2.13 TRAVIS_NODE_VERSION=4
    - MONGOVERSION=3.4.4 TRAVIS_NODE_VERSION=4
    - MONGOVERSION=3.6.0 TRAVIS_NODE_VERSION=4
