language: elixir
elixir:
  - 1.3.2
cache:
  - apt
  - directories:
    - ~/.mongodb
before_install:
  - npm install -g mongodb-version-manager
  - m use $MONGOVERSION
  - mkdir db
before_script:
  - sudo service mongodb stop
  - export PATH=$(m path):$PATH
  - mongod --fork --logpath mongo.log --dbpath db
env:
  matrix:
    - MONGOVERSION=2.4.14 TRAVIS_NODE_VERSION=4
    - MONGOVERSION=2.6.12 TRAVIS_NODE_VERSION=4
    - MONGOVERSION=3.0.12 TRAVIS_NODE_VERSION=4
    - MONGOVERSION=3.2.10 TRAVIS_NODE_VERSION=4
notifications:
  recipients:
    - eric.meadows.jonsson@gmail.com
