sudo: required
language: elixir

elixir:
  - 1.5
  - 1.6
  - 1.7
  - 1.8

cache:
  - apt
  - directories:
    - ~/.mongodb
    - ./plt_core_path

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g mongodb-version-manager
  - m use $MONGOVERSION
  - bash ./start_mongo.bash
  - mkdir db

before_script:
  - export PATH=$(m path):$PATH
  - echo $PATH
  - mongod --fork --logpath mongo.log --dbpath db

script:
  - mix test
  - not_allowed=(1.4 1.5)
  # - case "${not_allowed[@]}" in  *"${TRAVIS_ELIXIR_VERSION}"*) dialyzer=0 ;; *) dialyzer=1 ;; esac
  # - if [ "$dialyzer" -eq 1 ]; then mix dialyzer --halt-exit-status; fi

env:
  matrix:
    - MONGOVERSION=3.4.20 TRAVIS_NODE_VERSION=4
    - MONGOVERSION=3.6.12 TRAVIS_NODE_VERSION=4
    - MONGOVERSION=4.0.9 TRAVIS_NODE_VERSION=4
